# Generated by Django 4.2.2 on 2023-08-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/brands'),
        ),
        migrations.AlterField(
            model_name='car',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='cars/images'),
        ),
    ]
