# Generated by Django 4.2.2 on 2023-08-02 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='renter',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renters.wilaya'),
        ),
    ]
